
apiVersion: v1
kind: Config
preferences: {}

clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMvakNDQWVhZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJeU1EWXhOakF5TlRZME9Wb1hEVE15TURZeE16QXlOVFkwT1Zvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTElpCk9EV21GREtWRi9rR3daRnRuZzQ1NVdFTU9vU0NraURkbFlYcmZwQVF6QnRwanpwTVl5UEhCcUt5TDd4SkVOdDAKTDJLM3BZbkdHSFZiRFpsWnJPVmMvajJRZGQxYytKK2I5aVM1a2xrM2UvZkdidFVZZzVoVUVIa05aK2JlNmN6MwpFYXJPWWxGRS9XbjZvVGdjR0VpM3I3L1RIbGFISFBrTVJNcU9DbXhvaHBxUnQwcHNBa3lXT04yUk80N3U3VE1TClNnUUgrS1FWVU9BckJYYTFkSkNLV3lOVHlycGxreHZjY3ExdXZyM1EzSnB0ZWpJdWNmbnZWRW1VVkVnSW5RVHoKdUg4T21yMXNkbnNUcUttZ3l5U01VZHJMMkRjSWtKckhHYXh4SVBHK0Y5MjBRanFkQ0tLb0lOakFTdkFTY0VFVwp3S1VDUE5NbWpmK3Z6UVZTeThNQ0F3RUFBYU5aTUZjd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZBNGd3TWx1V0t0Smg1Y2tNOHNFTFlBK2ZyYi9NQlVHQTFVZEVRUU8KTUF5Q0NtdDFZbVZ5Ym1WMFpYTXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBSVkyNXJWemhaVkJ1ZENDNkhZTQpKZlp6VUV5OWpNeHBjOUFseWozV0FyVnhPcGVIMUt1UnFObjZvZlN2b0k4NWV0NnFCZmZFL0dqQmFhRWtiVXJrClN3TDV0OWh0bFdxSEFXQUNtVVU3WmIweTNKSnFnTnY0azAySm4rL0NxalJDcnZhRFVacm9OL0FnSkZKVXJFWkcKYndOVTFUZG5JMDdHajFYa05ZV3dsRE8zbnpFcVBMVGx3Q3ZZRnlzV3FlVDhXNHlaTmErOWlKaEdjNFVrSXpLVQpFVlB3OFFZc1k4V0tVY3ZQemdURWhVWUVFZDN4SnZLeTUwcUlpc1J1b1haT21zeGtHUmM4VlNLZmdxbEpseVR4CnRTV1M3bGJGRS82ektEaWgrWVkzSHg2NGMzQ1MxTTluQWdFb2E0cFh2TnF0QVEyYTNkWng2ZHdPenRqVlFOTTMKZS9vPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://3c9e282c-ce8c-414a-a71c-28b0d8e28b61.cpc2-us-central.linodelke.net:443
  name: lke64028

users:
- name: lke64028-admin
  user:
    as-user-extra: {}
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6ImlBRnVYckF6Z1F4N1d4cjlZbTZMY0xGVlVPTXBHQ0tBNUVYeW1JNnZOSk0ifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJsa2UtYWRtaW4tdG9rZW4temprODkiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoibGtlLWFkbWluIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiMzIxYTlmMjItYmYxYS00NzM2LWExOWUtZGUxMTYyZjdjZWU5Iiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50Omt1YmUtc3lzdGVtOmxrZS1hZG1pbiJ9.VJ7Vp0LdZyKq0ii-N9LobWmJs7lE-PT084KH6TyVYYWgxCvhAcv-IGTk579Xh7Nlpy1XPRKLz3kvy60Zz_1E9XcVIddVxuZrKbWInFCjH5BP4azZbYqNSrgZMCs7WQp7crr67ZzD9KoF2SThzWUTxapF5QUQgvnUnTV2pqTE4NxoDYDGrmME_cAqOVQk2M5RUrG0W0SFLLj3duEshI9MEPtolmr3VVtYfEpv9gKENpSmdlzsB5fMqnvqTJ-Fdk0VtZOi6zZ20TmVnUqFFG7is3CoYsXL-HERhb1ynC3SSDcv5TvWcO9b0l8QwfQa5RGw2J0egI6B7xNxXK5NfzzF1g

contexts:
- context:
    cluster: lke64028
    namespace: default
    user: lke64028-admin
  name: lke64028-ctx

current-context: lke64028-ctx